---
- hosts: all
  tasks:
    - name: Start organizr
      docker_container:
        name: organizr
        image: lsiocommunity/organizr
        restart_policy: always
        env:
          PGID: 1000
          PUID: 1000
        ports:
          - 8080:80
        volumes:
          - /home/docker/organizr:/config
